<template>
  <section class="bg-white py-20">
    <div class="container mx-auto">
      <div class="section-wrapper mx-5 md:mx-20">
        <h1 class="text-dark font-bold text-2xl md:text-4xl md:mx-12 text-center">
          <span class="text-primary"> But,</span> what is the difference between a Macro-Influencer
          and a Micro-Influencer?
        </h1>
        <p class="text-center text-gray mt-8 md:mx-16">
          One of the most significant differences is the fact that many micro-influencers have much
          higher engagement rates than macro-influencers (this is why I always tell my clients NOT
          to look at the followers count). >
        </p>
        <p class="text-center text-gray mt-8">
          A study by SocialPubli showed that micro-influencers generate 7x more engagement than the
          average generated by macro-influencers. They are not just the fastest-growing but also the
          most engaging category of influencers in the industry.
        </p>
        <p class="text-center text-gray mt-5">
          Sure, they have fewer followers than macro-influencers. But their followers are people who
          have a genuine interest in their content. Their followers are, therefore, more likely to
          engage with the content they post, even when it’s sponsored.
        </p>
      </div>
    </div>
  </section>
</template>
